=== JackyXiangcheng/XMLHomework/Assignment1/SpyBase2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ENTITY % p "(#PCDATA)">
<!ENTITY % c "CDATA">

<!ELEMENT info (spy*)>
<!ELEMENT spy (alias*, mission*)>
<!ELEMENT alias %p;>
<!ELEMENT mission (date, description, status)>
<!ELEMENT date %p;>
<!ELEMENT description %p;>
<!ELEMENT status %p;>

<!ATTLIST spy spyID ID #REQUIRED
			  firstname %c; #REQUIRED
			  lastname %c; #REQUIRED>
<!ATTLIST alias aID %c; #REQUIRED>
<!ATTLIST mission mID ID #REQUIRED>

=== JackyXiangcheng/XMLHomework/Assignment1/SpyBase2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE info SYSTEM "SpyBase2.dtd">
<!-- 被2013 sp1 () 使用XMLSpy v编辑的 (http://www.altova.com) by -->
<info>
	<spy spyID="A001" firstname="Nikki" lastname="Devgood">
		<alias aID="1">Spy Grrrl</alias>
		<alias aID="2">LaFemme Nikki</alias>
		<mission mID="M101">
			<date>2005/4/15</date>
			<description>Crack the code</description>
			<status>Mission Accomplished</status>
		</mission>
		<mission mID="M102">
			<date>2006/2/15</date>
			<description>Get the source</description>
			<status>Mission Accomplished</status>
		</mission>
		<mission mID="M103">
			<date>2006/5/4</date>
			<description>Hit the target</description>
			<status>In Progress</status>
		</mission>
	</spy>
	<spy spyID="A006" firstname="Link" lastname="Lister">
		<alias aID="3">LL</alias>
		<alias aID="4">Fred</alias>
		<mission mID="M104">
			<date>2006/6/15</date>
			<description>Shoot the rapid</description>
			<status>In Progress</status>
		</mission>
	</spy>
	<spy spyID="A003" firstname="Danger" lastname="Mause">
		<alias aID="5">Big Ears</alias>
		<mission mID="M105">
			<date>2005/11/4</date>
			<description>Get the &lt;big cheese&gt;</description>
			<status>In Progress</status>
		</mission>
		<mission mID="M106">
			<date>2006/4/4</date>
			<description>Map the area</description>
			<status>In Progress</status>
		</mission>
	</spy>
	<spy spyID="A099" firstname="Barbara" lastname="Feldon">
		<mission mID="M107">
			<date>2006/5/2</date>
			<description>Get Smart</description>
			<status>In Progress</status>
		</mission>
	</spy>
	<spy spyID="A004" firstname="Maxwell" lastname="Smart">
		<alias aID="6">Inspector Gadget</alias>
		<alias aID="7">Don Adams</alias>
		<mission mID="M108">
			<date>1967/2/15</date>
			<description>Protect Chief</description>
			<status>In Progress</status>
		</mission>
		<mission mID="M109">
			<date>2006/6/15</date>
			<description>Get some style</description>
			<status>Mission Accomplished</status>
		</mission>
	</spy>
</info>
